# LOAD BALANCER 1
- name: Setting up Redis Cluster loadbalancer 1
  hosts: lb1
  become: true
  become_method: sudo

  tasks:
  - name: Add main repository
    command: add-apt-repository main
  
  - name: Add universe repository
    command: add-apt-repository universe
  
  - name: Add restricted repository
    command: add-apt-repository restricted
  
  - name: Add multiverse repository
    command: add-apt-repository multiverse

  - name: Update repositories and install virtualbox and vagrant
    apt: 
      name: "{{ packages }}"
      update_cache: yes
    vars:
      packages:
      - virtualbox
      - vagrant

  - name: Create folder to copy configs
    command: mkdir -p lb-config

  - name: Copy haproxy.sh to master folder
    copy: 
      src: "{{ playbook_dir }}/../lb/master/haproxy.sh"
      dest: ./lb-config/

  - name: Copy keepalived configuration to master folder
    copy: 
      src: "{{ playbook_dir }}/../lb/master/keepalived.conf.master"
      dest: ./lb-config/

  - name: Copy Vagrantfile to master folder
    copy: 
      src: "{{ playbook_dir }}/../lb/master/Vagrantfile"
      dest: ./lb-config/
  
  - name: Copy rc.local to /etc folder
    copy:
      src: "{{ playbook_dir }}/../lb/master/rc.local"
      dest: /etc/
  
  - name: Setting rc.local execution permission
    file: dest=/etc/rc.local mode=a+x

  - name: Launch loadbalancer 1 VM
    command: chdir=/home/girs/lb-config vagrant up --provision

# LOAD BALANCER 2
- name: Setting up Redis Cluster loadbalancer 2
  hosts: lb2
  become: true
  become_method: sudo

  tasks:
  - name: Add main repository
    command: add-apt-repository main
  
  - name: Add universe repository
    command: add-apt-repository universe
  
  - name: Add restricted repository
    command: add-apt-repository restricted
  
  - name: Add multiverse repository
    command: add-apt-repository multiverse

  - name: Update repositories and install virtualbox and vagrant
    apt: 
      name: "{{ packages }}"
      update_cache: yes
    vars:
      packages:
      - virtualbox
      - vagrant

  - name: Create folder to copy configs
    command: mkdir -p lb-config

  - name: Copy haproxy.sh to backup folder
    copy: 
      src: "{{ playbook_dir }}/../lb/backup/haproxy.sh"
      dest: ./lb-config/

  - name: Copy keepalived configuration to backup folder
    copy: 
      src: "{{ playbook_dir }}/../lb/backup/keepalived.conf.backup"
      dest: ./lb-config/

  - name: Copy Vagrantfile to backup folder
    copy: 
      src: "{{ playbook_dir }}/../lb/backup/Vagrantfile"
      dest: ./lb-config/
  
  - name: Copy rc.local to /etc folder
    copy:
      src: "{{ playbook_dir }}/../lb/master/rc.local"
      dest: /etc/

  - name: Setting rc.local execution permission
    file: dest=/etc/rc.local mode=a+x
    
  - name: Launch loadbalancer 2 VM
    command: chdir=/home/girs/lb-config vagrant up --provision
