Vagrant.configure("2") do |config|
    config.vm.box = "debian/stretch64"

    # Configuration Load balancer 1
    config.vm.define "lb1" do |lb1_config|
        lb1_config.vm.provider :virtualbox do |vb_config|
            vb_config.name = "HAProxy + keepalived 1"
        end
        lb1_config.vm.hostname = "lb1"
        lb1_config.vm.network "private_network", ip: "192.168.100.100"
        lb1_config.vm.network :forwarded_port, guest: 80, host: 8080
        lb1_config.vm.network :forwarded_port, guest: 9000, host: 9000
        lb1_config.vm.provision :shell, path: "haproxy.sh"
        lb1_config.vm.provision :shell, inline: "cp /vagrant/keepalived.conf.master /etc/keepalived/keepalived.conf"
        lb1_config.vm.provision :shell, inline: "systemctl start keepalived"
    end

    # Configuration Load balancer 2
    config.vm.define "lb2" do |lb2_config|
        lb2_config.vm.provider :virtualbox do |vb_config|
            vb_config.name = "HAProxy + keepalived 2"
        end
        lb2_config.vm.hostname = "lb2"
        lb2_config.vm.network "private_network", ip: "192.168.100.200"
        lb2_config.vm.network :forwarded_port, guest: 80, host: 8082
        lb2_config.vm.network :forwarded_port, guest: 9000, host: 9002
        lb2_config.vm.provision :shell, path: "haproxy.sh"
        lb2_config.vm.provision :shell, inline: "cp /vagrant/keepalived.conf.backup /etc/keepalived/keepalived.conf"
        lb2_config.vm.provision :shell, inline: "systemctl start keepalived"
    end
end