Vagrant.configure("2") do |config|
    config.vm.box = "debian/contrib-stretch64"

    # Configuration Load balancer 2
    config.vm.define "lb2" do |lb2_config|
        lb2_config.vm.provider :virtualbox do |vb_config|
            vb_config.name = "HAProxy + keepalived 2"
        end
        lb2_config.vm.hostname = "lb2"
        lb2_config.vm.network "public_network", ip: "192.168.215.211", bridge: "enp2s0"
        lb2_config.vm.network :forwarded_port, guest: 80, host: 8080
        lb2_config.vm.network :forwarded_port, guest: 9000, host: 9000
        lb2_config.vm.provision :shell, path: "haproxy.sh"
        lb2_config.vm.provision :shell, inline: "cp /vagrant/keepalived.conf.backup /etc/keepalived/keepalived.conf"
        lb2_config.vm.provision :shell, inline: "systemctl start keepalived"
    end
end 